export 'dart:async';
export 'dart:math';

// export 'package:cloud_firestore/cloud_firestore.dart';
export '../../core/export_files/export_files.dart';
export '../../core/utils/constants/colors.dart';
export '../../core/utils/constants/images.dart';
export '../../core/utils/constants/list.dart';
export '../../core/utils/constants/size.dart';
export '../../core/utils/constants/string.dart';
export '../../core/utils/constants/style.dart';
export '../../core/utils/themes/custom/app_bar.dart';
export '../../core/utils/themes/custom/bottom_sheet.dart';
export '../../core/utils/themes/custom/check_box_theme.dart';
export '../../core/utils/themes/custom/chip_theme.dart';
export '../../core/utils/themes/custom/elevated_button.dart';
export '../../core/utils/themes/custom/size.dart';
export '../../core/utils/themes/custom/text_field_theme.dart';
export '../../core/utils/themes/custom/text_theme.dart';
// export 'package:car_app/firebase_options.dart';
// export 'package:car_app/presentations/authentication/forgot_pass.dart';
// export 'package:car_app/presentations/authentication/login.dart';
// export 'package:car_app/presentations/authentication/login_sign_up.dart';
// export 'package:car_app/presentations/authentication/profile_screen.dart';
// export 'package:car_app/presentations/authentication/schedule_screen.dart';
// export 'package:car_app/presentations/authentication/sign_up.dart';
// export 'package:car_app/presentations/authentication/sign_up_screen.dart';
// export 'package:car_app/presentations/authentication/verification_code.dart';
// export 'package:car_app/presentations/controllers/ambulance/ambulance_controller.dart';
// export 'package:car_app/presentations/controllers/auth/auth_controller.dart';
// export 'package:car_app/presentations/controllers/auth/profile_controller.dart';
// export 'package:car_app/presentations/controllers/doc/doc_controller.dart';
// export 'package:car_app/presentations/controllers/hospitals/hospital_controller.dart';
// export 'package:car_app/presentations/controllers/pharmacy_controller.dart';
// export 'package:doc_kit/presentations/on_board/on_board1.dart';
// export 'package:car_app/presentations/on_board/on_board2.dart';
// export 'package:car_app/presentations/on_board/on_board3.dart';
// export 'package:car_app/presentations/on_board/on_boarding.dart';

// export 'package:car_app/presentations/views/.dart';
// export 'package:car_app/presentations/views/.dart';
// export 'package:car_app/presentations/views/.dart';
// export 'package:car_app/presentations/views/.dart';
// export 'package:car_app/presentations/views/.dart';
// export 'package:car_app/presentations/views/.dart';
// export 'package:car_app/presentations/views/.dart';
// export 'package:car_app/presentations/views/.dart';
// export 'package:car_app/presentations/views/.dart';
// export 'package:car_app/presentations/views/.dart';
// export 'package:car_app/presentations/views/.dart';
// export 'package:car_app/presentations/views/.dart';
// export 'package:car_app/presentations/views/.dart';
// export 'package:car_app/presentations/views/.dart';
// export 'package:car_app/presentations/widgets/.dart';
// export 'package:car_app/presentations/widgets/.dart';
// export 'package:car_app/presentations/widgets/.dart';
// export 'package:car_app/presentations/widgets/.dart';
// export 'package:car_app/presentations/widgets/.dart';
// export 'package:car_app/presentations/widgets/.dart';
// export 'package:car_app/presentations/widgets/.dart';
// export 'package:car_app/presentations/widgets/.dart';
// export 'package:car_app/presentations/widgets/.dart';
// export 'package:car_app/presentations/widgets/.dart';
// export 'package:car_app/presentations/widgets/.dart';
// export 'package:car_app/presentations/widgets/.dart';
// export 'package:car_app/presentations/widgets/.dart';
// export 'package:car_app/presentations/widgets/.dart';
// export 'package:car_app/presentations/widgets/.dart';
// export 'package:car_app/presentations/widgets/.dart';
// export 'package:car_app/presentations/widgets/.dart';
// export 'package:car_app/presentations/widgets.dart';
// export 'package:car_app/presentations/widgets/.dart';
export '../../routes/routes.dart';

export '../../routes/routes_name.dart';
// export 'package:firebase_auth/firebase_auth.dart';
// export 'package:firebase_core/firebase_core.dart';
export 'package:flutter/material.dart';
// export 'package:font_awesome_flutter/font_awesome_flutter.dart';
export 'package:get/get.dart';
export 'package:google_fonts/google_fonts.dart';
export 'package:iconsax/iconsax.dart';

// export '../../widgets/container_shadow.dart';
// export '../../widgets/info_text.dart';
// export '../../widgets/left_clipper_widget.dart';
// export '../../widgets/left_middle_clipper_widget.dart';
// export '../../widgets/side_clipper_shaper.dart';
// export 'package:page_transition/page_transition.dart';
// export 'package:smooth_page_indicator/smooth_page_indicator.dart';
